#docker run -d -rm -name mongo -p 27017:27017 -v mongo-data:/data/db mongo:latest

version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672   # RabbitMQ server port
      - 15672:15672 # RabbitMQ management UI port
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  
volumes:
  mongodbdata:
  rabbitmqdata:
